server:
  port: 8083

spring:
  application:
    name: notification-service

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      group-id: loan-notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

kafka:
  topics:
    loan-applications: loan-applications

aws:
  region: us-east-1
  dynamodb:
    table-name: loan-notifications
    endpoint: http://localhost:4567
  s3:
    bucket-name: loan-audit-logs
    endpoint: http://localhost:4567
  use-local: true