server:
  port: 8081

spring:
  application:
    name: application-service

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  datasource:
    url: jdbc:postgresql://localhost:5433/loanunderwriting
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

  data:
    redis:
      host: localhost
      port: 6380
      timeout: 2000ms

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

kafka:
  topics:
    loan-applications: loan-applications

services:
  underwriting-service:
    url: http://localhost:8082
  ai-decision-service:
    url: http://localhost:8084

loan:
  rules:
    max-loan-amount: 1000000
    min-credit-score: 580
    max-debt-to-income-ratio: 0.43