server:
  port: 8082

spring:
  application:
    name: underwriting-service

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  datasource:
    url: jdbc:postgresql://localhost:5433/loanunderwriting
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      group-id: underwriting-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

  data:
    redis:
      host: localhost
      port: 6380
      timeout: 2000ms

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

kafka:
  topics:
    loan-applications: loan-applications

services:
  application-service:
    url: http://localhost:8081
  ai-decision-service:
    url: http://localhost:8084

underwriting:
  rules:
    min-credit-score: 580
    max-debt-to-income-ratio: 0.43
    max-loan-amount: 1000000
    min-annual-income: 20000